# Generated by Django 3.0.1 on 2020-01-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
