# Generated by Django 3.0.1 on 2020-01-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
